on:
  push:
    branches:
      - main
      - "feature/**"
      - "fix/**"
    paths-ignore:
      - "**/*.md"
      - .scafflater/**

  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - .scafflater/**
  workflow_dispatch:
  repository_dispatch:
      types: ["Standard"]


name: Standard

env:
  app_name: "Testes Automação Cinemark Web"
  aws_region: "us-east-1"
  dockerfilePath: "dockerfiles/Dockerfile"
  namespace: "Cinemark-Robot-Framework"
  value_stream: "robot-selenium"
  BASE_URL: ${{ vars.BASE_URL }}
  #BASE_API: ${{ vars.BASE_API }}

jobs:
  ci_web:
    name: CI - Test Cinemark Web
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3
      - name: ⚙️ Default Steps
        uses: ./.github/actions/setup-composite
      - name: 🧪 Run Cinemark Web Robot Tests
        run: |
          mkdir -p LogWebCinemarkReports
          robot -d LogWebCinemarkReports ./src/Selenium/TestCases
        continue-on-error: true
      - name: ⬆️ Upload Cinemark Web Test results
        uses: actions/upload-artifact@v4
        with:
          name: web-report
          path: LogWebCinemarkReports

#ENVIO DE RESULTADO DOS TESTES EXECUTADOS PARA O SLACK:
  report_slack:
    name: CI - ENVIA STATUS REPORT PARA SLACK
    needs: [ci_web]
    if: always ()
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Python Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: /opt/hostedtoolcache/Python/
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: pip-
      - name: ⬇️ Download web Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-report
          path: ./artifacts/core
      - name: 📁 Move Reports Without Unzipping
        run: |
          mkdir -p LogWebCinemarkReports 
          mv ./artifacts/web/* LogWebCinemarkReports
      - name: 📨 Run Envio de Msg para Slack com Resultado dos Testes
        run: |
          robot -t Report_Tests ./Helpers/Envia_msg_Slack.robot
      - name: ⬆️ Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report
